### ISSUE TITLE
SEG Fault

### ISSUE THREAD

**Issue by 1ay1** [theandrew168/srgp#1]
Hi @theandrew168,

Not an issue, but wanted to know if you know what's actually causing the Segmentation Fault in the original code?

**Comment by theandrew168** [comment]
@0xfe0 Are you referring to the version of the code currently in this repo's `src/` directory or the original code from [Brown's Software Catalog](https://cs.brown.edu/software/)? Additionally, which example in particular is triggering the seg fault? I haven't worked on this project in quite a while but will try and help figure it out.

**Comment by 1ay1** [comment]
Both repos give this:
```
SRGP FATAL ERROR:
   X SERVER ERROR
  (examining the core will be useful only if using X in synchronous mode):
         BadMatch (invalid parameter attributes)


I AM ABOUT TO INTENTIONALLY CRASH SO YOU CAN LOOK
      AT THE ACTIVATION STACK USING A DEBUGGER.

If your application is an SRGP application, please remember:
   If the error message above says
   that you sent a bad argument to a certain function,
   you should run your program with tracing ON in order
   to see exactly what you sent.
If you already had tracing enabled, remember to look in
   'SRGPlogfile' for the tracing messages.


Thread 1 "show_patterns" received signal SIGABRT, Aborted.
0x00000000ffffe458 in ?? ()
```

**Comment by theandrew168** [comment]
@0xfe0 Alright, thanks for this trace! I'll take a look.

**Comment by theandrew168** [comment]
Alright, I had some time to take a look at this. Interestingly, the error I get on my machine is slightly different. It is still an X11 usage error but instead of a `BadMatch` I get a `BadAccess`. The program then aborts as expected. As to what is _specifically_ causing the X server errors here, I'm not sure.

From what I've been able to discern, the SRGP codebase interacts with X11 in ways that are deprecated and/or invalid by today's standards. Its been 30+ years since this code was written so the API decay isn't super surprising. These types of "using the X11 API wrongly" are scattered throughout the original codebase in ways that are tough to isolate.

This is what led to me to start the rewrite from scratch (keeping the same SRGP API while completely overhauling how it interacts with X11). Unfortunately, I wasn't able to finish the rewrite. There weren't any notable blockers or anything like that: I simply got busy with other projects.

Even today, however, detailed documentation surrounding proper usage of the low-level X11 APIs is a bit hard to come by. The most notable resource is [Christopher Tronche's X Window System Reference](https://tronche.com/gui/x/). Unless an X11 expert appears that could pinpoint what's incorrect about the current X11 API usage, it'd be a troubleshooting deep dive. In my opinion, finishing the rewrite would be the most effective way to make SRGP useful again. I'm still busy with other projects these days, but contributors are always welcome!

**Comment by 1ay1** [comment]
Hi again,

I'm thinking of re-implementing SRGP, I saw your re-write and its fine, I might take your re-write forward but breaking it down into several source files.
But I was thinking of writing it in [GDK ](https://docs.gtk.org/gdk3/) instead of X11, that way it will be cross-platform.
What do you think?

**Comment by theandrew168** [comment]
@0xfe0 I think that'd be a great project! One thing to keep in mind, however, is that some of the SRGP API surface area leaks its X11 implementation details a bit (bitmap / pixmap patterns, color tables, etc). Other than those hiccups, I'd love to see SRGP rebased onto a modern GUI toolkit.

**Comment by 1ay1** [comment]
Hi @theandrew168 , I have finished the rewrite of SRGP, all the functions are working fine, I have tested it with all the examples(tests), please feel free to test it yourself and it will be nice if you can help me with bring it on autotools, so that the deployment is easy.

https://github.com/0xfe0/SRGP

**Comment by theandrew168** [comment]
@0xfe0 That's awesome! Great work on the rewrite.

Regarding autotools, what are your goals for deployment? To package and distribute the shared library as a deb / rpm package? Or just use for local development? Either way, I personally prefer a simple Makefile to autotools and therefore don't have much experience with the latter.

**Comment by 1ay1** [comment]
Yes, simple makefile will be nice too, just want to package it so that people can just install it on their systems.
